# Generated by Django 5.2.2 on 2025-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'Link',
            },
        ),
    ]
